apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  labels:
    mon: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: service-promotheus
  labels:
    mon: prometheus
spec:
  ports:
    - port: 9090
  selector:
    mon: prometheus
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-prometheus
  labels:
    mon: prometheus
spec:
  selector:
    matchLabels:
      mon: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mon: prometheus
    spec:
      containers:
      - image: prom/prometheus
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus
        - name: pvc-prometheus-mount
          mountPath: /etc/prometheus/data
      volumes:
      - name: prometheus-config-volume
        configMap:
            defaultMode: 420
            name: prometheus-config

      - name: pvc-prometheus-mount
        persistentVolumeClaim:
          claimName: pvc-prometheus
