apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  selector:
    matchLabels:
      name: mysql-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.14.0
        imagePullPolicy: IfNotPresent
        env:
        - name: DATA_SOURCE_NAME
          value: "root:admin@(10.97.240.227:3306)/"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 9104
 
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
spec:
  selector:
    name: mysql-exporter
  ports:
    - name: prom
      port: 9104
      targetPort: 9104
      protocol: TCP
