apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos7
spec:
  selector:
    matchLabels:
      app: centos7
  replicas: 1
  template:
    metadata:
      labels:
        app: centos7 
    spec:
      containers:
      - name: centos7
        image: c:a7
